import Link from 'next/link';
import { ArrowLeft, ArrowRight, Bot, Mail, MessageSquare, Plus, Save, Sheet, Sparkles } from 'lucide-react';
import AppShell from '../../components/AppShell';

const palette = [{ icon: Mail, name: 'Send email', type: 'Gmail' }, { icon: MessageSquare, name: 'Post message', type: 'Slack' }, { icon: Sheet, name: 'Append row', type: 'Google Sheets' }, { icon: Bot, name: 'AI classify', type: 'Agent' }];

export default function Builder() {
  return <AppShell active="workflows"><main className="builder-page"><div className="builder-top"><div><Link className="back-link" href="/workflows"><ArrowLeft size={15} /> Workflows</Link><h1>New workflow</h1></div><div className="builder-actions"><button className="secondary-button"><Save size={16} /> Save draft</button><button className="primary-button">Publish workflow <ArrowRight size={16} /></button></div></div><div className="builder-grid"><aside className="node-palette"><p className="eyebrow">Node palette</p><h2>Build your flow</h2><p className="muted">Drag a node onto the canvas to begin.</p>{palette.map(({ icon: Icon, name, type }) => <button className="palette-node" key={name}><span><Icon size={16} /></span><div><b>{name}</b><small>{type}</small></div><Plus size={15} /></button>)}</aside><section className="canvas"><div className="canvas-toolbar"><span><i className="live-dot" /> Draft canvas</span><button><Sparkles size={15} /> Generate with AI</button></div><div className="flow-grid"><div className="flow-node trigger"><small>TRIGGER</small><b>When a new invoice arrives</b><span>Gmail inbox</span></div><div className="connector" /><div className="flow-node"><small>AGENT</small><b>Classify invoice</b><span>Planner + AI</span></div><div className="connector" /><div className="flow-node"><small>ACTION</small><b>Route to finance</b><span>Slack message</span></div><button className="add-node"><Plus size={18} /></button></div></section><aside className="config-panel"><p className="eyebrow">Configuration</p><h2>Classify invoice</h2><label>Node name<input defaultValue="Classify invoice" /></label><label>Instruction<textarea defaultValue="Identify the vendor, amount, and department from the invoice." /></label><div className="config-note"><Sparkles size={15} /><span>Agent output is validated before the next step runs.</span></div></aside></div></main></AppShell>;
}
