import Link from 'next/link';
import { ArrowLeft, ArrowRight, Bot, Mail, MessageSquare, Plus, Save, Sheet, Sparkles } from 'lucide-react';
import AppShell from '../../components/AppShell';
import { createWorkflow, generateWorkflow } from '../../services/api';
import { useState } from 'react';
import { useRouter } from 'next/router';

const palette = [{ icon: Mail, name: 'Send email', type: 'Gmail' }, { icon: MessageSquare, name: 'Post message', type: 'Slack' }, { icon: Sheet, name: 'Append row', type: 'Google Sheets' }, { icon: Bot, name: 'AI classify', type: 'Agent' }];

export default function Builder() {
  const router = useRouter();
  const [nodes, setNodes] = useState([{ id: 'trigger-1', type: 'trigger', label: 'When a new invoice arrives', provider: 'gmail' }, { id: 'agent-1', type: 'agent', label: 'Classify invoice', provider: 'gemini' }, { id: 'action-1', type: 'action', label: 'Route to finance', provider: 'slack' }]);
  const [message, setMessage] = useState('');
  const [busy, setBusy] = useState(false);
  const save = async (status) => { setBusy(true); setMessage(''); try { const payload = { name: 'Invoice routing', description: 'Classify invoices and route them to the right team.', status, nodes, edges: nodes.slice(1).map((node, index) => ({ id: `edge-${index}`, source: nodes[index].id, target: node.id, animated: true })), triggerConfig: { type: 'manual' }, tags: ['generated'] }; const { data } = await createWorkflow(payload); setMessage(status === 'active' ? 'Workflow published.' : 'Draft saved.'); if (status === 'active') await router.push(`/workflows/${data.workflow.id}`); } catch (error) { setMessage(error.response?.data?.error || 'Unable to save workflow. Please sign in again.'); } finally { setBusy(false); } };
  const addNode = ({ name, type }) => setNodes((current) => [...current, { id: `${type}-${Date.now()}`, type: type.toLowerCase(), label: name, provider: type.toLowerCase() }]);
  const generate = async () => { setBusy(true); setMessage(''); try { const { data } = await generateWorkflow({ prompt: 'When an invoice arrives, classify it and route it to finance.' }); setNodes(data.workflow.nodes.map((node) => ({ id: node.id, type: node.type, label: node.data.label, provider: node.data.provider }))); setMessage('Workflow generated.'); } catch (error) { setMessage(error.response?.data?.error || 'Unable to generate workflow.'); } finally { setBusy(false); } };
  return <AppShell active="workflows"><main className="builder-page"><div className="builder-top"><div><Link className="back-link" href="/workflows"><ArrowLeft size={15} /> Workflows</Link><h1>New workflow</h1></div><div className="builder-actions"><button className="secondary-button" onClick={() => save('draft')} disabled={busy}><Save size={16} /> Save draft</button><button className="primary-button" onClick={() => save('active')} disabled={busy}>Publish workflow <ArrowRight size={16} /></button></div></div>{message && <p className="form-error">{message}</p>}<div className="builder-grid"><aside className="node-palette"><p className="eyebrow">Node palette</p><h2>Build your flow</h2><p className="muted">Add a node to your canvas.</p>{palette.map(({ icon: Icon, name, type }) => <button className="palette-node" key={name} onClick={() => addNode({ name, type })}><span><Icon size={16} /></span><div><b>{name}</b><small>{type}</small></div><Plus size={15} /></button>)}</aside><section className="canvas"><div className="canvas-toolbar"><span><i className="live-dot" /> Draft canvas</span><button onClick={generate} disabled={busy}><Sparkles size={15} /> Generate with AI</button></div><div className="flow-grid">{nodes.map((node, index) => <>{<div className={`flow-node ${node.type}`} key={node.id}><small>{node.type.toUpperCase()}</small><b>{node.label}</b><span>{node.provider}</span></div>}{index < nodes.length - 1 && <div className="connector" key={`connector-${node.id}`} />}</>)}</div></section><aside className="config-panel"><p className="eyebrow">Configuration</p><h2>{nodes[1]?.label || 'Select a node'}</h2><label>Node name<input value={nodes[1]?.label || ''} onChange={(event) => setNodes((current) => current.map((node, index) => index === 1 ? { ...node, label: event.target.value } : node))} /></label><label>Instruction<textarea defaultValue="Identify the vendor, amount, and department from the invoice." /></label><div className="config-note"><Sparkles size={15} /><span>Agent output is validated before the next step runs.</span></div></aside></div></main></AppShell>;
}
